### ISSUE TITLE
Literature Review: Air Travel Demand Forecasts

### ISSUE THREAD

**Issue by michaelweinold** [sustainableaviation/demandmap#1]
Welcome on board, @dodedic and @arebe337!

I suggest we start this project by conducting a [_systematic_ literature review](https://en.wikipedia.org/wiki/Systematic_review).

 - Collect traffic forecasts (scope: until 2050) from:
     - industry orgs (IATA, Airlines4America, Waypoint2050, etc.)
     - consultancies (McK, BCG, etc.)
     - airlines (only when the forecasts include global data)
     - government agencies (EASA, FAA, etc.)
     - scientific publications (Scholar, Scopus, Lens, etc.)

> [!NOTE]
> Remember to note the search terms you use for finding scientific publications (eg. `TITLE-ABS-KEY(aviation AND forecast)`.
 
Add all forecast documents to Zotero (`Aviation > 4 Economics > Future Demand`) AND to [the Excel sheet](https://ethz-my.sharepoint.com/:x:/r/personal/mweinold_ethz_ch/Documents/Semester%20Project%202024/Literature%20Review/Traffic%20Forecast%20Literature%20Review.xlsx?d=w65445ce4e8e44e6e93792fe3b052b6f3&csf=1&web=1&e=uPAE1c)

**Comment by arebe337** [comment]
I've started looking for various reports on air transport forecasts.
- I've created new folders in Zotero so that we can separate the reports from the scientific publications.
-  So far, I haven't come across any reports from different consultancy companies or airlines. 
- Additionally, I couldn't find an online license for the ACI World Airport Traffic Forecasts 2023–2052. @michaelweinold, do you have any ideas on where we could obtain one? I believe this report could be beneficial for our case. 

I'll  start looking  for scientific publications tomorrow.

**Comment by michaelweinold** [comment]
> Additionally, I couldn't find an online license for the ACI World Airport Traffic Forecasts 2023–2052. @michaelweinold, do you have any ideas on where we could obtain one? I believe this report could be beneficial for our case.

From what I can see, [these are rather expensive](https://store.aci.aero/product/aci-world-airport-traffic-forecasts-2023-2052/). If these reports do turn out to be hugely benefitial to our research, I can get in touch with my contacts at Zurich Airport (the experts from the Aviation I lecture). But even then, we should know _exactly_ what data we need from the reports.

**Comment by arebe337** [comment]
> From what I can see, [these are rather expensive](https://store.aci.aero/product/aci-world-airport-traffic-forecasts-2023-2052/). If these reports do turn out to be hugely benefitial to our research, I can get in touch with my contacts at Zurich Airport (the experts from the Aviation I lecture). But even then, we should know _exactly_ what data we need from the reports.

I also only found the paid version. I had hoped there might be a way to access the data for university research purposes, but if that's not the case, I think that we should be able to gather enough data from other sources.

**Comment by michaelweinold** [comment]
> I had hoped there might be a way to access the data for university research purposes

Feel free to call or write to the company, but don't expect too much 😇. I do think we can get data through Zurich Airport - perhaps we can use it to benchmark results towards the end of the project.

**Comment by michaelweinold** [comment]
Thank you for the update. Just to clarify:

> [!IMPORTANT]
> We are looking for _any_ traffic forecast. \
> This includes reports that provide these metrics: pax-km, ASK, flights, fuel burn, CO2 emissions, etc.

On the subject of academic publications:

> focus on predicting the future increase in carbon dioxide emissions rather than forecasting the rising number of passengers

I expect that _every_ paper that contains data on future CO2 emissions will have used some kind of traffic forecast. This is because CO2 emissions _per passenger_ depend heavily on factors such as pax-per-acft, etc.

For instance, my colleague Romain recently published this: https://doi.org/10.1038/s41467-023-39749-y. He used traffic forecasts to calculate related CO2 emissions. Add this publication and the underlying forecast to the Zotero folder and to the Excel sheet.

Until Wednesday, I expect that all reports you found are added to the Excel sheet (which is currently empty 😢):

<img width="552" alt="Screenshot 2024-03-08 at 15 31 43" src="https://github.com/sustainableaviation/demandmap/assets/23102087/085bd65c-50ea-4999-925e-36fbe6700a52">

If possible, you should plot the reports, as per:

 - https://github.com/sustainableaviation/demandmap/issues/2

**Comment by arebe337** [comment]
@michaelweinold I began working on the table. Here some challenges I encountered:
- It can be quite challenging to obtain all the assumptions made by various sources. Some provide minimal insights, while others make over 20 different assumptions. Do you have any suggestions on how we should approach this?
- Many reports rely on similar sources but make adjustments for their results. Perhaps we could include this information in an additional column?

**Comment by michaelweinold** [comment]
> (...) while others make over 20 different assumptions. Do you have any suggestions on how we should approach this?

Could you give an example?

> Perhaps we could include this information in an additional column?

Sure, makes sense.
