### ISSUE TITLE
Estimate API Cost

### ISSUE THREAD

**Issue by michaelweinold** [sustainableaviation/demandmap#12]
...since our friends at ADB are not very responsive, we might need to [purchase API access](https://rapidapi.com/aedbx-aedbx/api/aerodatabox/pricing) like a commercial client. Please estimate how much our use case would cost us.

**Comment by dodedic** [comment]
Whipped up a quick PDF for ease of sharing the information. Is this up to standard for you to show McKenna?

[Cost Estimation API.pdf](https://github.com/sustainableaviation/demandmap/files/14918979/Cost.Estimation.API.pdf)

**Comment by dodedic** [comment]
@michaelweinold 
We have a bit of change here. I contacted the ADB-Team about the API request we will use for the flight data and they confirmed what I thought might be true: One API request **returns the data for 7 days** and not just one specified date. See screenshot:

![image](https://github.com/sustainableaviation/demandmap/assets/118805682/7227498f-1614-4c3e-bfce-d3b9b260a706)

This would leave us with the following new numbers for the [**Cost Estimation API.docx**](https://github.com/sustainableaviation/demandmap/files/14933384/Cost.Estimation.API.docx)
