### ISSUE TITLE
Find City Pairs for Rail Infrastructure Cost Calculation

### ISSUE THREAD

**Issue by michaelweinold** [sustainableaviation/demandmap#14]
We (@michaelweinold, @dodedic) discussed the possibility of estimating/calculating construction costs of rail infrastructure with Bastian Weissenburger (Fraunhofer/ETHZ) on 17.04.2024. During his previous research, he constructed a model that would do just that - except for pipelines (gas, oil, Hydrogen, etc.).

The motivation for this is the following:

Once we have API access, we will be able to calculate the future air travel demand between a city pair, based on current demand and GDP growth projections. We could then try to estimate how high carbon prices would need to be for the construction of rail infrastructure to become economically viable. This would significantly improve the impact of our project.

As @dodedic pointed out, we should try to avoid routes that introduce uncertainties for which we might be righty criticised. This might include:

1. Mountain ranges with significant slopes (pipelines can traverse higher inclination before tunnelling becomes necessary)
2. City pair with existing rail links (we would need to research how cost is reduced if infrastructure pre-exists)
3. City pairs where the distance is so large that people are unlikely to change to a rail connection

Since, as we know, most growth will come from developing nations, how about looking for routes between major cities in Africa or SE-Asia?

While I originally had this example in mind, the distance might be too large:

<img width="1486" alt="Screenshot 2024-04-18 at 07 56 55" src="https://github.com/sustainableaviation/demandmap/assets/23102087/d023373b-d1f1-4f9d-b7f1-d20e13f612e0">

I suggest you come up with a few options.

**Comment by dodedic** [comment]
@michaelweinold @arebe337 
Based on [this paper](https://www.hindawi.com/journals/jat/2017/8426926/) which compares High Speed Rail (HSR) to air transport on different city pairs across Europe, Asia and North America HSR dominates the passenger share on routes that are between 200-1200km long.
This boils down partly to travel time, comfort, no hassle of security checks/boarding and the fact that with HSR you end up immediately in the city centre. 

With this information we want to look at **major city pairs** that are currently missing a HSR connection but show either strong air transport demand or could develop it in the future.

**Sydney - Melbourne**
_~900km, 9.3mio PAX 2023_
With this being in the [top 10 most profitable air transport city pairs (OAG)](https://www.oag.com/busiest-routes-right-now) it would certainly provide a good example to calculate with. Also the terrain seems adequate for what we discussed. Would definitely pass this route onto Bastian for a trial.

![image](https://github.com/sustainableaviation/demandmap/assets/118805682/6c2aebcd-0d2d-4b58-b68b-1630c1af2c79)

**Durban-Johannesburg**
_~600km_
Two of the three largest airports in South Africa in terms of PAX movements. Question here is elevation/terrain from Durban to Johannesburg.

![image](https://github.com/sustainableaviation/demandmap/assets/118805682/8b88562e-dce9-4608-84ec-b97a4654926f)

**San Francisco-Los Angeles**
_~600km, 3.9mio PAX 2019_
This project is already in construction with an inital cost estimate of around 40 billion USD but is massively over budget. From a transport standpoint this is the perfect use case for HSR.

![image](https://github.com/sustainableaviation/demandmap/assets/118805682/909ef3cd-fb9a-46be-bb9e-fdf0baf469fd)

**Jeddah-Riyadh**
_~600km, 7.9mio PAX 2023_
There is an existing HSR from Jeddah up to Medina which would only require an extension to Riyadh. This is one of the top 10 busiest air transport routes in the world.

![image](https://github.com/sustainableaviation/demandmap/assets/118805682/82af833b-7be6-4260-b1a8-66ded03bfd0a)

**Mumbai-Bangalore**
_~1000km, 3.8mio PAX 2019_
India as an emerging market with strong predicted GDP growth could be interesting for such a HSR connection. Terrain also looks good. This is currently one of the busiest air transport routes in the world (3.8mio PAX 2019)

![image](https://github.com/sustainableaviation/demandmap/assets/118805682/f94bad81-649f-43e1-90f8-20710a4f69d4)

**Bangkok-Phuket**
_~1000km, 3.6mio PAX 2019_
Slightly more difficult terrain. Strong air travel demand. Like India emerging sector.

![image](https://github.com/sustainableaviation/demandmap/assets/118805682/380251e6-7fc8-486d-a63e-5b51948adb6b)

**Comment by michaelweinold** [comment]
Thank you @dodedic for compiling this list of potential city pairs.

I would suggest:

1. Look for one city pair where efforts (or studies) to construct new rail infrastructure are already underway. For example: Australia or California. We can then ask Bastian to model this route and compare his results against real-world data.
2. Look for one city pair with _no_ existing rail infrastructure, in a developing country with large expected GDP growth.

**Comment by dodedic** [comment]
1. For both San Francisco - LA & Melbourne - Sydney there are the actual route and the latest government proposal from 2013 respectively:

<img src="https://github.com/sustainableaviation/demandmap/assets/118805682/8df6b337-a15b-4f44-af09-73ecbc1b160c" height="400">

<img src="https://github.com/sustainableaviation/demandmap/assets/118805682/7bc8c3a9-6dc7-489b-a1a2-7dfaebd62611" height="400">

2. I think a good city pair to look at in developing countries could be **Abuja - Lagos (Nigeria)**. It is one of the busiest air routes in Africa (according to Routes) with good terrain for HSR. Nigeria is expected to have [>3% GDP growth per year](https://www.imf.org/external/datamapper/NGDP_RPCH@WEO/OEMDC/ADVEC/WEOWORLD) up until 2029. While there is _some_ rail infrastructure in Nigeria on that route, a train trip from Abuja to Lagos takes about 15h.

<img src="https://github.com/sustainableaviation/demandmap/assets/118805682/88dac987-c1dc-4bd7-a703-81acd15afea8" height="400">

**Comment by michaelweinold** [comment]
@dodedic:

> For both San Francisco - LA & Melbourne - Sydney there are the actual route and the latest government proposal (...)

> I think a good city pair to look at in developing countries could be Abuja - Lagos (Nigeria).

Looks great - please draft an email to Bastian informing him of our choice.
I would need to go back to the recording to check if he needs values for $/km (rail) _before_ or _after_ he runs it through his model.

**Comment by dodedic** [comment]
I am fairly certain he doesn't need the actual value of $/km for the route calculation at all, since it is solely based on the _cost factors_ that are applied to the terrain. The actual cost in $/km can then just be mutliplied by said factors.

Saying that, I am now still looking to find those cost factors for the laying of tracks instead of pipelines. I will draft an E-Mail and send it to you today with some factors from [this paper](https://github.com/sustainableaviation/demandmap/files/15149958/1-s2.0-S1877042814000895-main.pdf).
