### ISSUE TITLE
Poster Draft

### ISSUE THREAD

**Issue by michaelweinold** [sustainableaviation/demandmap#16]
<img width="715" alt="Screenshot 2024-04-24 at 19 22 58" src="https://github.com/sustainableaviation/demandmap/assets/23102087/345829fd-9a47-4561-8254-36407616f404">

**Comment by michaelweinold** [comment]
Open questions (for discussion between @dodedic and @arebe337):

 - [ ] What kind of map to show? Some ideas: map with 2024 or 2050 levels of demand, map with demand growth 2024-2050, etc.
 - [ ] What additional information to show in the map? Some ideas: Number of annual pax at every airport, etc.
 - [ ] Select studies of GDP/RPK correlation to show in a small table on top of the relevant figure (see draft sketch).

**Comment by michaelweinold** [comment]
New draft:

<img width="715" alt="Screenshot 2024-05-18 at 16 24 07" src="https://github.com/sustainableaviation/demandmap/assets/23102087/2012a8b2-f858-4d80-8f1e-b7635e73f6f1">

**Comment by michaelweinold** [comment]
New draft:

<img width="715" alt="Screenshot 2024-05-18 at 16 24 07" src="https://github.com/sustainableaviation/demandmap/assets/23102087/89aa0f1b-c5b2-4dcc-8fd1-f7134762786c">

**Comment by michaelweinold** [comment]
@dodedic, please add:

 - [ ] benchmarking data for all case-study routes (https://github.com/sustainableaviation/demandmap/issues/11#issuecomment-2132392131)
 - [ ] future passenger projections for all case-study routes
 - [ ] CO2 calculations for _one_ case study route only

@arebe337, please provide some metrics on our data collection:

 - [ ] # of unique connections
 - [ ] # of total flights
 - [ ] # of airports covered)

**Comment by arebe337** [comment]
@MichaelWeinold

- 106,873 unique connections
- ~36,700,000 total flights (estimated based on the 7-day average of one week per month, extrapolated to the entire month, and then summed up for all months)
- 3,132 departing airports covered

**Comment by dodedic** [comment]
@michaelweinold 

See my Excel sheet and some information [here](https://github.com/sustainableaviation/demandmap/issues/11#issuecomment-2133567377).
