### ISSUE TITLE
API Call Script

### ISSUE THREAD

**Issue by michaelweinold** [sustainableaviation/demandmap#18]
...open a PR when ready.

**Comment by dodedic** [comment]
@michaelweinold Since now we have all the files from all airports and one week of each month, should those be included in the PR? Since it kind of bypasses the ADB API and would "give away" all that API-data in this repo?

**Comment by michaelweinold** [comment]
No, I would suggest you keep the files in a ETHZ OneDrive directory and read them into the Python scripts from there. Neither the API key nor the queried data must make it into the repository.

**Comment by arebe337** [comment]
@dodedic I think this issue can also be closed?
