### ISSUE TITLE
Plot Demand Forecasts

### ISSUE THREAD

**Issue by michaelweinold** [sustainableaviation/demandmap#2]
Please add all forecasts to a `matplotlib` figure. I just provided a draft in https://github.com/sustainableaviation/demandmap/commit/0dcea89c7b037e2f596e517722adfc1a79e944ef: `figures/forecasts_literature`

**Comment by dodedic** [comment]
Hi @michaelweinold!

If I understood you correctly you would like a single plot projecting the different forecasts against each other, or do you simply want the information from each forecast plotted uniformly all in different figures?

**Comment by michaelweinold** [comment]
...a single plot makes more sense. We would like to compare them, ultimately. Just add more lines to [this template I provided.](https://github.com/sustainableaviation/demandmap/blob/main/figures/forecasts_literature/forecasts_literature.pdf)

**Comment by michaelweinold** [comment]
...and, [as I mentioned](https://app.element.io/#/room/!tHpfFJousgsiCnyPpl%3Amatrix.org/%24OcPVQmH4vWJFqKPHFPi0pLMiTPX19F-zRgpwueaZUYk?via=matrix.org), I would like a PR!

**Comment by arebe337** [comment]
- [ ] add real IATA RPK until 2023
 - [ ] separater starting forcast data
 - [ ] unify baseline for all forecast
 - [ ] separate plot for Europe

**Comment by dodedic** [comment]
- We added the IATA data
- Made some corrections on the scale of the numbers (billions, trillions etc.) to make sure they are correct now in RPKs
- We distinguish real data to forecasts with the real data being a dotted line and the forecasts as solid lines (more visually pleasing than a vertical line in my opinion)
- For the Europe plot we realised that the data from Eurocontrol, however accurate it is, is given in IFR movements instead of RPKs. Should we still go ahead with plotting that? @michaelweinold

**Comment by michaelweinold** [comment]
...best you push your changes to [the PR](https://github.com/sustainableaviation/demandmap/pull/5) soon. You can omit Eurocontrol data if their unit of interest is movements.

**Comment by arebe337** [comment]
- [] change coulures
- [] vertical line for date
- [] legend into bottom right
- [] adjust ATI at 2050
- [] rename axes

**Comment by michaelweinold** [comment]
I updated the figure with some cosmetic changes - and removed the `read_excel` option that threw a depreciation warning:

```
<ipython-input-1-e08e10f2e5a0>:47: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
```

**Comment by michaelweinold** [comment]
@arebe337, once you selected some nice colors (or "coulures", whatever you prefer 😎) - could you add a forecast for global GDP growth? Perhaps an upper/lower bound would work best. We can also color the are in between - but that's a detail for our next meeting.

<img width="1456" alt="Screenshot 2024-03-22 at 12 39 18" src="https://github.com/sustainableaviation/demandmap/assets/23102087/2c9a7d60-c648-42fa-9697-205fc869ad42">
