### ISSUE TITLE
Problem with plotting (Geopanda)

### ISSUE THREAD

**Issue by arebe337** [sustainableaviation/demandmap#22]
While attempting to plot the data of the world map, I encountered some issues for which I have not yet found a solution:
- It appears that with GeoPandas, it is only possible to draw straight lines between two points, and it does not adjust the lines to the curvature of the earth. Instead, it always takes the shortest distance on the map rather than the actual distance on the earth.
- Currently, flights from America to Asia (both ways) are shown as going over Europe instead of over the Pacific, which is the actual route in real life. It seems like Geopanda can't calculate distances that go outside of the coordinate system. 

In my search for solutions, I came across Plotly, which seems to offer a possible solution for both of our problems! Since Plotly also works with Pandas, switching to this library would not pose a significant challenge. Additionally, for the interactive map that we intend to create at a later point, I read that GeoPandas is quite limited compared to Plotly in that regard.

[Here](https://plotly.com/python/lines-on-maps/) is a link to the Plotly documentation for drawing lines on maps for your reference.

**Comment by michaelweinold** [comment]
I would concur. It seems that GeoPandas is currently well-suited to plotting tabulated data directly - [for basic geospatial data only](https://coolum001.github.io/geopandasdisplay.html). 

Alternatives for more sophisticated plotting (incl. great circle distances, awareness of map boundaries, etc.) are:

 - [`geoplot`](https://residentmario.github.io/geoplot/index.html#), which is a wrapper for:
 - [`cartopy`](https://scitools.org.uk/cartopy/docs/v0.14/index.html)

The documentation of both projects is... somewhat lacking. I was much happier with the GeoPandas documentation.

...but, evidently, [there is also Plotly](https://plotly.com/python/choropleth-maps/#using-geopandas-data-frames). 

The good news: [Panel is compatible with Plotly](https://panel.holoviz.org/reference/panes/Plotly.html). This means that we should be able to quickly add interactive maps to the [WASM-based dashboard website](https://aviation.psi.ch/en/latest/).

I would therefore suggest, @arebe337 & @dodedic: Go ahead and plot with Plotly. I am looking forward to the first iteration of the map.

Just for reference: I mentioned previously that I had already collected some information on different plotting libraries [here](https://github.com/sustainableaviation/docs/blob/main/source/content/dashboard.md).
