### ISSUE TITLE
Determine best RPK Baseline

### ISSUE THREAD

**Issue by michaelweinold** [sustainableaviation/demandmap#3]
...one option for a reliable source:

Chart 2 in [IATA 12-2023 Air Passenger Market Analysis](https://www.iata.org/en/iata-repository/publications/economic-reports/air-passenger-market-analysis-december-2023)

You can extract data using the [WebPlotDigitizer](https://apps.automeris.io/wpd/).

**Comment by michaelweinold** [comment]
You can close this issue if you're happy with the baseline you extracted from IATA.

**Comment by michaelweinold** [comment]
@dodedic:

> You can close this issue if you're happy with the baseline you extracted from IATA.

**Comment by dodedic** [comment]
This can be closed, yes! (Don't have permission to close it myself)
