### ISSUE TITLE
Extract GPS Coordinates from Maps of "Proposed Rail Lines"

### ISSUE THREAD

**Issue by michaelweinold** [sustainableaviation/demandmap#34]
I will extract the coordinates of the proposed rail lines - that will allow us to quickly calculate the mean deviation of our calculated route from the proposed route.

Since we need to adjust for the different map projections, I will need the GPS coordinates of the cities on the maps (city center should be fine).

<img src="https://github.com/sustainableaviation/demandmap/assets/23102087/f54de92b-5593-4cb2-bde6-01d890f8031e" width="300">
<img src="https://github.com/sustainableaviation/demandmap/assets/23102087/0beabb50-28df-45cd-8c10-d4e2c9ffd46e" width="300">

**Comment by michaelweinold** [comment]
Could you provide a list of the cities and their coordinates? Then I can correct the maps and extract the coordinates of the rail lines.

**Comment by dodedic** [comment]
@michaelweinold 

Los Angeles
Latitude: 34.0522° N
Longitude: 118.2437° W

San Francisco
Latitude: 37.7749° N
Longitude: 122.4194° W

Melbourne
Latitude: 37.8136° S
Longitude: 144.9631° E

Sydney
Latitude: 33.8688° S
Longitude: 151.2093° E

**Comment by michaelweinold** [comment]
...if it was just the four, I would have done it myself 🙈 To correct for map projection, I need the points of all cities on the maps.

**Comment by dodedic** [comment]
> ...if it was just the four, I would have done it myself 🙈 To correct for map projection, I need the points of all cities on the maps.

Ah I see, I was wondering that hahaha.

Here you go:
[City_Centers_California_Australia.xlsx](https://github.com/sustainableaviation/demandmap/files/15403880/City_Centers_California_Australia.xlsx)

**Comment by michaelweinold** [comment]
@dodedic, could you check the extracted data?

[extacted_tracks.zip](https://github.com/sustainableaviation/demandmap/files/15405545/extacted_tracks.zip)

**Comment by dodedic** [comment]
@michaelweinold 
Here ya go! 😄 What do we make of this? Would it make sense to also feed some cities inbetween S.F. and LA  into Bastian's model, or would that distort the point of what we are trying to achieve?

![image](https://github.com/sustainableaviation/demandmap/assets/118805682/b4a6b2f5-2459-415d-861f-6c6580a46fac)

P.S. 
No spaces in file names, has been changed! 😜 

![image](https://github.com/sustainableaviation/demandmap/assets/118805682/6f956869-7a68-4b3e-b999-87613f409f8a)

**Comment by michaelweinold** [comment]
...how does the Australia example look like? I would suggest you email Bastian with a nicely formatted Excel list of cities that the rail lines should "connect" - I am sure he can quickly re-run the simulation.

**Comment by dodedic** [comment]
> ...how does the Australia example look like?

If I am not being completely stupid right now, the file you sent me only includes the California example.

**Comment by michaelweinold** [comment]
Ah, ok - in that case, you'll get the coordinates tomorrow.

**Comment by dodedic** [comment]
Alright! I will message Bastian in the meantime.
