### ISSUE TITLE
Create Draft of Air Transport Figures

### ISSUE THREAD

**Issue by michaelweinold** [sustainableaviation/demandmap#7]
While we are working on obtaining the necessary data, we should start preparing the corresponding visualizations.

I suggest we use [geopandas](https://geopandas.org), rather than [https://scitools.org.uk/cartopy/docs/latest/](https://scitools.org.uk/cartopy/docs/latest/) since it is better documented - and should offer all features we need.

For now, assume that we have data on ~20 airports in Europe and all flights between them.

Our figure should now show:

1. All flights between these airports (great circle only)
2. The number of flights (frequency)

You can use my lecture figures as templates for using geopandas: [`map_corsia_euets`](https://github.com/michaelweinold/phd_publication_figures/tree/main/4_sustainable_aviation/map_corsia_euets) and [`route_ban_france`](https://github.com/michaelweinold/phd_publication_figures/tree/main/4_sustainable_aviation/route_ban_france).

Here are two ideas we could adapt ([image #1 source](https://www.buzzfeednews.com/article/peteraldhous/busiest-day-flights), [image #2 source](https://www.visualcapitalist.com/cp/mapping-airways-the-worlds-flight-paths-and-airports/)):

<img width="796" alt="image" src="https://github.com/sustainableaviation/demandmap/assets/23102087/fd8e98e9-9247-4165-8621-b4ad9e0c9101"> 
<img width="796" alt="image" src="https://github.com/sustainableaviation/demandmap/assets/23102087/1658a939-c7f5-408a-8651-26bca17db854">

**Comment by arebe337** [comment]
@michaelweinold I started working on the map for Europe! It looks quite okay so far. I've included the 20 biggest airports on the map, but I'm having trouble finding data for the connections between them. Do you have any ideas where I can find this information?

**Comment by michaelweinold** [comment]
Right now, just make up some sample data.

**Comment by arebe337** [comment]
I think we could maybe get the data from here: https://ec.europa.eu/eurostat/web/transport/data/database

**Comment by arebe337** [comment]
I still have to adjust the code with comments and some adjustment that it follows all rules... sorry that I already committed
